// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const CButton: typeof import("@casual-ui/svelte")["CButton"]
    const CCheckbox: typeof import("@casual-ui/svelte")["CCheckbox"]
    const CForm: typeof import("@casual-ui/svelte")["CForm"]
    const CFormItem: typeof import("@casual-ui/svelte")["CFormItem"]
    const CInput: typeof import("@casual-ui/svelte")["CInput"]
    const openNotification: typeof import("@casual-ui/svelte")["openNotification"]
    const PageTitle: typeof import("./../src/components/PageTitle/src/PageTitle.svelte")["default"]
    const ThemeSwitch: typeof import("./../src/components/ThemeSwitch/src/ThemeSwitch.svelte")["default"]
}

export {}
